In [ ]:
import numpy as np

In [ ]:
arr =np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

Vectors and Matrix


In [ ]:
b = np.arange(1,7)
b

array([1, 2, 3, 4, 5, 6])

In [ ]:
a = np.arange(1,100,5)
a

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [ ]:
c =np.zeros((4,6))
c

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

linspace
generates number in range provided

In [ ]:
arr1  = np.linspace(1,5,100)
arr1

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

Random

In [ ]:
s = np.random.rand(1,4)
s

array([[0.66530467, 0.35767576, 0.12238819, 0.68835896]])

In [ ]:
ss = np.random.randint(1,100,30)
ss

array([84, 80, 66,  7, 30,  1, 69, 78, 85, 49, 11, 47,  7, 11, 87, 58, 72,
       26, 31, 75, 22, 54, 99, 91, 75, 61, 51, 75, 18, 14])

In [ ]:
w = np.array([[1,2,3],[4,5,6],[7,8,9]])
w

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Sum :
if axis =0 (add cols) else add rows

In [ ]:
np.sum(w,axis=0)

array([12, 15, 18])

Reshaping and resizing


In [ ]:
q = np.arange(1,25)
q = q.reshape((4,6))
print(q)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


Array Indexing and slicing

In [ ]:
e = np.arange(1,17)
e

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
e[3:11]

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
e[3::8]

array([ 4, 12])

In [ ]:
rum = np.arange(1,31).reshape(6,5)
rum

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
rum[0]

array([1, 2, 3, 4, 5])

In [ ]:
rum[:0]

array([], shape=(0, 5), dtype=int64)

In [ ]:
rum[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [ ]:
rum[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

Boolean Indexing

In [ ]:
qq =np.arange(11,21)
qq

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
boo = qq%2==0
boo

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [ ]:
ww = qq[boo]
ww

array([12, 14, 16, 18, 20])

Arithmatic operations: 2 vars must have equal elements


In [ ]:
a1 = np.array([1,2,3,4])
a2 = np.array([2,3,4,5])
a3 = a1+a2
a3

array([3, 5, 7, 9])

In [ ]:
arr1 = np.arange(1,56)
arr1 = arr1.reshape(5,11)
arr1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
arr1 +=10
arr1

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65]])

Deep and Shalow copy

In [ ]:
arr1 = np.arange(1,17)
new=arr1[2:13]*10

new


array([ 30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130])

Deep Copy = No change in original even if you modify the copy (subset or not).

Meaning:

You take a part of the original (subset), but create a deep copy of it

If you modify that deep copy
→ the original will NOT change


ARITHMATIC OPERATION === DEEP COPY




In [ ]:
shallow = arr1[1:4]
shallow[0]=999
print("Original",arr1)
print("Shallow:",shallow)

Original [  1 999   3   4   5   6   7   8   9  10  11  12  13  14  15  16]
Shallow: [999   3   4]


Matrix Operations


In [ ]:
A =np.array([[1,2,3],[4,4,7]])
B = np.array([[1,1],
              [3,6],
              [7,7]])
A


array([[1, 2, 3],
       [4, 4, 7]])

In [ ]:
B

array([[1, 1],
       [3, 6],
       [7, 7]])

In [ ]:
A @ B
np.dot(A,B)

array([[28, 34],
       [65, 77]])

Transpose

In [ ]:
A.T

array([[1, 4],
       [2, 4],
       [3, 7]])

Array manipulation

In [ ]:
#requires same no of cols
A = np.array([1,2])
B = np.array([2,5])
C = np.vstack((A,B))
C



array([[1, 2],
       [2, 5]])

In [ ]:
c = np.hstack((A,B))
c

array([1, 2, 2, 5])

Split


| Function        | Meaning          | Splits Along | Works On      | Equal Sections      |
| --------------- | ---------------- | ------------ | ------------- | ------------------- |
| **hsplit**      | horizontal split | columns      | 2D array      | columns must divide |
| **vsplit**      | vertical split   | rows         | 2D array      | rows must divide    |
| **array_split** | general split    | any axis     | any dimension | no restriction      |





In [ ]:
np.hsplit(c,2)

[array([1, 2]), array([2, 5])]

In [ ]:
c = np.array([1,2,3,4])
c2 = c.reshape(2,2)
np.vsplit(c2,2)

[array([[1, 2]]), array([[3, 4]])]